# Configuración del servidor
#server:
 #port: 8082

# Configuración de la aplicación Spring
spring:
  application:
    name: CUSTOMER-MS
  mvc:
    throw-exception-if-no-handler-found: true  # Para que arroje una excepción si no encuentra un controlador para una ruta.

  # Configuración de la base de datos
  datasource:
    url: jdbc:mysql://autorack.proxy.rlwy.net:25967/railway
    username: root
    password: WzvqTyAqnqQGihPaPjtWDtJBtoRfWKbz
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# Configuración de SpringDoc para OpenAPI y Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    url: /openapi.yaml



# Configuración de Eureka
eureka:
  client:
    service-url:
      defaultZone: https://euraka-server-production.up.railway.app/eureka/
      #defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: false
    hostname: customer-ms-production.up.railway.app
    #hostname: localhost