openapi: 3.0.1
info:
  title: API de Microservicio Clientes
  version: 1.0.0
  description: Microservicio para la gesti贸n de clientes en un sistema bancario.

servers:
  - url: https://customer-ms-production.up.railway.app
    description: Servidor de producci贸n
  #url: http://localhost:8082
  #  description: Servidor local

paths:
  /cliente:
    get:
      summary: Obtener todos los clientes
      responses:
        '200':
          description: Lista de clientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cliente'
    post:
      summary: Crear un cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
      responses:
        '201':
          description: Cliente creado
        '400':
          description: Error de validaci贸n

  /cliente/{id}:
    get:
      summary: Obtener cliente por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalles del cliente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
        '404':
          description: Cliente no encontrado
    put:
      summary: Actualizar cliente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
      responses:
        '200':
          description: Cliente actualizado
        '400':
          description: Error de validaci贸n
        '404':
          description: Cliente no encontrado
    delete:
      summary: Eliminar cliente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Cliente eliminado
        '400':
          description: No se puede eliminar porque tiene cuentas activas
        '404':
          description: Cliente no encontrado

components:
  schemas:
    Cliente:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string
        apellio:
          type: string
        dni:
          type: string
        email:
          type: string
